# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 18:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISIN', models.CharField(max_length=14)),
                ('fund_name', models.CharField(max_length=50)),
                ('fund_country', models.CharField(max_length=3)),
                ('fund_type', models.CharField(max_length=30)),
                ('fund_objective', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FundPositionSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_percentage', models.FloatField()),
                ('position_quantity', models.FloatField()),
                ('position_currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FundSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=datetime.date)),
                ('fund_snapshot_value', models.FloatField()),
                ('fund_snapshot_comment', models.CharField(max_length=50000)),
                ('fund_snapshot_is_quarter_snapshot', models.BooleanField(default=False)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Fund')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISIN', models.CharField(max_length=14)),
                ('date', models.DateTimeField(verbose_name=datetime.date)),
                ('stock_exchange', models.CharField(max_length=15)),
                ('stock_currency', models.CharField(max_length=3)),
                ('stock_company', models.CharField(max_length=50)),
                ('stock_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=datetime.date)),
                ('stock_snapshot_adjusted_close', models.FloatField()),
                ('stock_snapshot_close', models.FloatField()),
                ('stock_snapshot_volume', models.FloatField()),
                ('stock_snapshot_high', models.FloatField()),
                ('stock_snapshot_low', models.FloatField()),
                ('stock_snapshot_is_quarter_snapshot', models.BooleanField(default=False)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='fundpositionsnapshot',
            name='fund_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.FundSnapshot'),
        ),
        migrations.AddField(
            model_name='fundpositionsnapshot',
            name='stock_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.StockSnapshot'),
        ),
    ]
