# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 22:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISIN', models.CharField(max_length=14)),
                ('fund_name', models.CharField(max_length=50)),
                ('fund_country', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FundSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=datetime.date)),
                ('value', models.FloatField()),
                ('comment', models.CharField(max_length=50000)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Fund')),
            ],
        ),
        migrations.CreateModel(
            name='FundSnapshotStockSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.FundSnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISIN', models.CharField(max_length=14)),
                ('date', models.DateTimeField(verbose_name=datetime.date)),
                ('exchange', models.CharField(max_length=3)),
                ('company', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=datetime.date)),
                ('value', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='fundsnapshotstocksnapshot',
            name='stock_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.StockSnapshot'),
        ),
    ]
