# Generated by Django 2.1.1 on 2018-09-07 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundpositionsnapshot',
            name='fund_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.FundSnapshot'),
        ),
        migrations.AlterField(
            model_name='fundpositionsnapshot',
            name='stock_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.StockSnapshot'),
        ),
        migrations.AlterField(
            model_name='fundsnapshot',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Fund'),
        ),
        migrations.AlterField(
            model_name='stocksnapshot',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Stock'),
        ),
    ]
